export const onboarding = {
  welcome: {
    title: 'Le dîner ce soir, déjà réglé.',
    body: '3 idées de repas pour votre famille, prêtes en 1 minute.',
    cta: 'Démarrer',
    subCta: 'Prêt en moins d\'1 minute',
  },
  household: {
    kicker: '01 · VOTRE FOYER',
    title: 'Combien êtes-vous à table ?',
    sub: 'Pour adapter les portions. Modifiable à tout moment.',
    kidsQ: 'DES ENFANTS PARMI EUX ?',
    agesQ: 'QUEL ÂGE ? · OPTIONNEL',
    agesNote: 'Pour proposer des recettes adaptées aux plus jeunes.',
    ageOptions: ['< 2 ans', '2–5 ans', '6–10 ans', '11+ ans'],
    cta: 'Continuer',
  },
  tastes: {
    kicker: '02 · GOÛTS',
    title: "Qu'est-ce qui vous fait plaisir ?",
    sub: '3 styles suffisent. Modifiable plus tard.',
    moreLink: 'Voir plus de styles · optionnel',
    discoveryLabel: 'OUVERT AUX NOUVEAUTÉS ?',
    cta: 'Continuer',
    subCta: 'Modifiable à tout moment dans Famille',
    styles: [
      'Rapide & facile',
      'Méditerranéen',
      'Asiatique',
      'Traditionnel français',
      'Végétarien',
      'Pasta & riz',
    ],
    extendedStyles: [
      'Grillades',
      'Soupes & veloutés',
      'Healthy & léger',
      'Tex-Mex',
      'Street food',
      'Cuisine du monde',
    ],
    moodOptions: [
      { value: 'classic' as const, title: 'Les classiques',      sub: "Ce qu'on aime, on le refait" },
      { value: 'mix'     as const, title: 'Variété & équilibre', sub: 'Un peu de tout, selon les envies' },
      { value: 'curious' as const, title: 'Nouvelles saveurs',   sub: 'On aime découvrir et surprendre' },
    ],
  },
  allergies: {
    kicker: '03 · ALLERGIES',
    title: 'Des allergies à signaler ?',
    sub: "On évitera ces ingrédients dans vos recettes.",
    otherLink: '+ Autre allergie',
    privacy: '🔒 Vos données restent privées.',
    cta: 'Continuer',
    options: ['Aucune', 'Gluten', 'Lactose', 'Fruits à coque', 'Œufs', 'Poisson', 'Crustacés'],
    extendedOptions: ['Soja', 'Sésame', 'Arachides', 'Moutarde', 'Sulfites', 'Céleri'],
  },
  fridge: {
    kicker: '04 · PREMIERS PRODUITS',
    title: "Qu'est-ce qu'on a dans le frigo ?",
    sub: 'Cochez ce que vous avez. ~ 20 secondes.',
    heroKicker: '⚡ DÉMARRAGE EXPRESS',
    heroTitle: 'Démarrage express',
    heroSub: '10 essentiels à cocher · 20 secondes',
    promises: [
      '✓ Suffit pour vos 3 premières idées de repas',
      '✓ On a deviné les essentiels pour vous',
      '✓ Vous compléterez quand vous voulez',
    ],
    items: [
      'Œufs', 'Pâtes', 'Riz', 'Pommes de terre', 'Oignons',
      'Fromage râpé', 'Lait', 'Beurre', 'Tomates', 'Poulet',
      'Carottes', 'Courgettes', 'Poivrons', 'Champignons', 'Épinards',
      'Thon en boîte', 'Lardons', 'Yaourt', 'Crème fraîche', 'Pain de mie',
      'Jambon', 'Saumon', 'Steak haché', 'Lentilles', 'Pois chiches',
      'Haricots verts', 'Petits pois', 'Brocoli', 'Concombre', 'Salade',
      'Pommes', 'Bananes',
    ],
    maxItems: 10,
    counter: (n: number, max: number) =>
      n === 0 ? 'Choisissez jusqu\'à 10 produits' : `${n} / ${max} produits sélectionnés`,
    skipLink: 'Plus tard',
    ctaEmpty: 'Démarrer quand même',
    cta: (count: number) => `Démarrer avec ces ${count} produits`,
    subCta: 'Quelques produits suffisent pour démarrer.',
  },
  ready: {
    kicker: '✨ TOUT EST PRÊT',
    title: 'Vos 3 recettes vous attendent.',
    sub: 'Adaptées à votre famille, à partir de vos produits.',
    summaryLabels: {
      household: 'foyer',
      tastes: 'goûts',
      allergies: 'allergies',
      fridge: 'frigo',
    },
    teaserKicker: 'BIENTÔT SUR VOTRE TABLE',
    cta: 'Découvrir mes 3 recettes ✨',
    subCta: '⏱ Environ 10 secondes',
    editLink: 'Modifier mes réponses',
  },
  cooking: {
    kicker: 'EN CUISINE',
    title: 'On prépare vos recettes…',
    titleDone: 'Et voilà !',
    checks: {
      stock:      (n: number) =>
        `Vos produits, c'est fait · ${n} utilisés`,
      tastes:     (list: string) =>
        `Vos goûts, c'est fait · ${list}`,
      family:     (a: number, k: number) =>
        `Votre famille, c'est fait · ${a} adulte${a > 1 ? 's' : ''}, ${k} enfant${k > 1 ? 's' : ''}`,
      generating: 'Création de vos recettes · presque prêt',
    },
    footer: 'Habituellement moins de 10 secondes',
    footerSlow: 'Encore quelques secondes…',
    footerRetry: 'Réessayer',
  },
}

export const quota = {
  normal: (remaining: number, total: number) => `${remaining} / ${total} ce mois`,
  low: (remaining: number) => `Plus que ${remaining} ce mois.`,
  empty: (resetAt: string) => `Plus de générations ce mois. Réinitialisation le ${resetAt}.`,
}
